In [9]:
import numpy as np
array = np.arange(start=10,stop=100,step=10)
print(array)

[10 20 30 40 50 60 70 80 90]


In [10]:
import numpy as np
array = np.arange(start=10,stop=100,step=10)
print(array)
print(array.dtype)
array = array.astype(np.float64)
print(array.dtype)
print (array)

[10 20 30 40 50 60 70 80 90]
int64
float64
[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [29]:
import numpy as np
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
print(" Original List: ",my_list)
my_list.pop()
print("Atfer Removing Last Element:",my_list)
my_list.insert(3, 22)
print("After Inserting to index 3:",my_list)
my_list = [2, 6, 11, 24, 8, 45, 25, 60]
my_array = np.array(my_list)
print("Np Array",my_array)

 Original List:  [2, 6, 11, 24, 8, 45, 25, 60]
Atfer Removing Last Element: [2, 6, 11, 24, 8, 45, 25]
After Inserting to index 3: [2, 6, 11, 22, 24, 8, 45, 25]
Np Array [ 2  6 11 24  8 45 25 60]


In [42]:
import numpy as np

two_d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12],
                        [13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]])
print("Original 2-D array:",two_d_array)



three_d_array = np.array([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]]])
print("\nOriginal 3-D array:",three_d_array)


split_arrays = np.vsplit(two_d_array, 3)

print("\nSplit 2-D arrays:")
for arr in split_arrays:
    print(arr)

Original 2-D array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Original 3-D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Split 2-D arrays:
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]]


In [48]:
import numpy as np

my_array = np.array([2, 20, 33, 40, 50, 60, 75, 83, 91, 99])


filter_array = my_array > 55

print("Original array:", my_array)
print("Values higher than 55:", my_array[filter_array])

Original array: [ 2 20 33 40 50 60 75 83 91 99]
Values higher than 55: [60 75 83 91 99]


In [50]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_indexes = np.where(my_array % 2 == 0)

print("Original array:", my_array)
print("Indexes of even values:", even_indexes)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Indexes of even values: (array([1, 3, 5, 7, 9]),)


In [57]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)
print("Original matrix:\n", matrix)

flattened_matrix = matrix.astype(float).flatten()
print("\nFloated array:", flattened_matrix)

print("\nMax:", np.max(flattened_matrix))
print("Min:", np.min(flattened_matrix))

Original matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Floated array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

Max: 10.0
Min: 2.0


In [65]:
random_numbers = np.random.randint(1, 1001, 150)
print(random_numbers)



[145 739 903 729 295 800 227 150 839  28 172 511 211  67 710 674 440 569
 831 816 487 343 278 326 240 321 618 548   9 765 316 470 461 138  27 107
 844 710 264 544 488 389 642 632 314 319 151 147 433  24 144 599 570 537
  88 904 749 897 174 974 926 742 163 687 841 369 629 791 756 936 127 987
 238 514 641 484 488 403 542 139 512 546 363 753 846 968 545 891 446 586
 715 645 431 425   3 684 917 752 167 850 469 217 827 772 215 786 536 720
 610 740 878 245  72 417  47 942  48 684 710 961 286 781 729 617 504 481
 498 583  42  73 612 104 656 234 624 956 290 609 662 600 455 956 352 498
 795 490 665   3 772 596]


In [66]:

# Find and print odd numbers
odd_numbers = random_numbers[random_numbers % 2 != 0]
print("\nOdd numbers in the array:")
print(odd_numbers)


Odd numbers in the array:
[145 739 903 729 295 227 839 511 211  67 569 831 487 343 321   9 765 461
  27 107 389 319 151 147 433 599 537 749 897 163 687 841 369 629 791 127
 987 641 403 139 363 753 545 891 715 645 431 425   3 917 167 469 217 827
 215 245 417  47 961 781 729 617 481 583  73 609 455 795 665   3]


In [69]:
# Function to find multiples of a given number n
def find_multiples(array, n):
    return array[array % n == 0]

n = 5
multiples_of_n = find_multiples(random_numbers, n)
print(f"\nMultiples of {n} in the array:")
print(multiples_of_n)


Multiples of 5 in the array:
[145 295 800 150 710 440 240 765 470 710 570 545 715 645 425 850 215 720
 610 740 245 710 290 600 455 795 490 665]


In [68]:
# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = random_numbers[np.vectorize(is_prime)(random_numbers)]
print("\nPrime numbers in the array:")
print(prime_numbers)


Prime numbers in the array:
[739 227 839 211  67 569 487 461 107 389 151 433 599 163 127 641 139 431
   3 167 827  47 617  73   3]


In [67]:
# Find and print even numbers
even_numbers = random_numbers[random_numbers % 2 == 0]
print("\nEven numbers in the array:")
print(even_numbers)


Even numbers in the array:
[800 150  28 172 710 674 440 816 278 326 240 618 548 316 470 138 844 710
 264 544 488 642 632 314  24 144 570  88 904 174 974 926 742 756 936 238
 514 484 488 542 512 546 846 968 446 586 684 752 850 772 786 536 720 610
 740 878  72 942  48 684 710 286 504 498  42 612 104 656 234 624 956 290
 662 600 956 352 498 490 772 596]
